### ISSUE TITLE
question for loaduri

### ISSUE THREAD

**Issue by holli73** [ChriD/Raumserver#12]
hello,

i used TUNEIN but i have minisatip + tvh running so all my listen channels are available direct from my satelite dish -> so i used now my own radio station and i'm not relaying on the internet or some provider.
i always had some problems dropped connection/get new ip from provider,...

no i use the loaduri to connect direct to my favorite streams direct from my satelite dish this works fine - but i don't get the channel logo/name displayed - what needs my interface to provide so this is shown in the webclient like it is for tunein -> logo/name?

any help would be great.

thanks
holli

**Comment by ChriD** [comment]
This is a known "enhancement issue" in the kernel and will be done if possible
 https://github.com/ChriD/RaumkernelLib/issues/2

**Comment by ChriD** [comment]
As Mentioned in the above link to the other issue, this si not possible with a nice amout of effort.
