### ISSUE TITLE
New request "power on" supporting new feature remote power control

### ISSUE THREAD

**Issue by davidspr** [ChriD/Raumserver#24]
Raumserver requests (e.g. play, stop,...) work if the Raumfeld device(s) is/are on or in standby/eco mode but they don't if the device(s) is/are switched off. However, the devices can be switched on via app using the new remote power control feature.
Is it possible to try switching the devices on (if off) before sending requests (e.g. play)? 

Source: https://us.raumfeld.com/meldung/raumfeld-introduces-smart-standby,-remote-power-control-and-android-widgets-14.html

**Comment by ChriD** [comment]
I have to check if RF provides the API for that.

**Comment by ChriD** [comment]
Requests are now available (see Wiki for info)
