### ISSUE TITLE
Raumfeld Firmware 1.57 popup prohibits RaumserverInstaller

### ISSUE THREAD

**Issue by rwitkamp** [ChriD/Raumserver#27]
Since the latest update op Raumfeld firmware the RaumserverInstaller does not work anymore. What has changed in the firmware is that now a user autentication popup (Welcome to Raumfeld (Release 1.57))appears when opening an SSH session to the Raumfeld device. It appears to me that the installer cannot deal with this popup so it says that there is no SSH possible.

**Comment by ChriD** [comment]
I know.
The reason for this is that SFTP was disabled in the new RF-Firmware. Instead it uses now SCP.
I have to update the installer to use SCP instead of SFTP.

**Comment by rwitkamp** [comment]
Good to hear you know the issue and solution. Good luck!

**Comment by seidel77** [comment]
Also, since the new release, I can't have SSH access...

**Comment by ChriD** [comment]
@seidel77 They have changed the Authentication mode from "Password" to "None". so Using Authentication "password" with the root user and an empty Passwort won't work. You have to use the "None" Authentication mode

**Comment by seidel77** [comment]
Ciao Chris,
Thanks for feed back - I can log in with SCP (putty or other soft) but I
can't get an SSH access with the file (UBS stick in, wait 1 mn and SSH
should be granted... - it doesn't work on 1.57 but on version 1.56 no
problem -
https://github.com/ChriD/Raumserver/wiki/How-to-get-SSH-Access-to-a-raumfeld-device)
).

2016-09-05 9:50 GMT+02:00 Christian notifications@github.com:

**Comment by ChriD** [comment]
Hmm... RF Has changed the internal app they use for SSH/SCP. Maybe they forgot somthing?
But since you can connect with SCP, SSH should work too.
I can't realy test this on my devices because they all got SSH access long time ago on older RF-Kernel Versions

I am using Bitvise, but i will try to connect per SSH with putty in the evening.

**Comment by seidel77** [comment]
Can I grant SSH access with bitwise or otherwise ? I can access the RF with
putty or other program but I don't know what to do to have the SSH access
(copy the file anywhere ?, modify some file ?). Can I also install the web
server manualy?
Would appreciate your help. - anyway - thanks for your soft, it's a great
work !

2016-09-05 12:21 GMT+02:00 Christian notifications@github.com:

**Comment by rwitkamp** [comment]
It seems they also changed the RSA host key. If you run into problems connecting to the RF device with this error message:

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED! @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!

Try this command on the PC where you connect from:

ssh-keygen -R {servername  or  IP adres}

**Comment by seidel77** [comment]
Hi, thanks for your help, I'm running win8 and the cmd is not recognising
the command... I also try to
download PortableGit-2.4.3.1-2nd-release-candidate-64-bit.7z to run
ssh-keygen but it doesn't work to.. really sorry. greatly appreciate your
help

2016-09-05 20:16 GMT+02:00 rwitkamp notifications@github.com:

**Comment by rwitkamp** [comment]
I run a Fedora Linux client to connect to the RF device. SSH and SSH-KEYGEN are by default included in that Linux distribution. I don't know how to do it in a Windows command prompt. Maybe this van help you:

https://help.netmail.com/display/KB/Clearing+Outdated+PuTTy+RSA+Keys+in+Window+Environments

**Comment by ChriD** [comment]
I have updated the installer to use the new scp. But i have problems rebooting the device via ssh. It doesnt work. I 'll try until saturday if i can achieve this. if not i will realease the installer without the automatic reboot of the device after install

**Comment by rwitkamp** [comment]
Sounds good! Compliments for the fast response! If a manual reboot is part of the installer process I think everyone can live with that!  Great work!

**Comment by ChriD** [comment]
i have updated the code on the git but i have to build binaries for linux and windows.
I'll do this soon. Im sorry that it takes so much time but i am very busy at the moment

**Comment by ChriD** [comment]
The new version with scp support is online now. you can Download it from the link in the old installer (he will tell you that there is a new version) or download it from here

**Comment by rwitkamp** [comment]
Thanks! It works!

Van: Christian [mailto:notifications@github.com] 
Verzonden: maandag 19 september 2016 19:01
Aan: ChriD/Raumserver
CC: rwitkamp; Author
Onderwerp: Re: [ChriD/Raumserver] Raumfeld Firmware 1.57 popup prohibits RaumserverInstaller (#27)

The new version with scp support is online now. you can Download it from the link in the old installer (he will tell you that there is a new version) or download it from here

**Comment by seidel77** [comment]
thanks a lot. it works perfectly!
