### ISSUE TITLE
raumserver aborts on windows if - the HOSTCONFIG changes

### ISSUE THREAD

**Issue by holli73** [ChriD/Raumserver#3]
hello,

i use the raumserver on windows but if i do a hostconfig change than the rauserver aborts (access violation).

thanks
holli

**Comment by ChriD** [comment]
Do you mean the Change of the RF-Host from one device to another?

**Comment by holli73** [comment]
hello,

yes in this situation the process aborts

thanks
holli

**Comment by ChriD** [comment]
Okay, Thanks. I'll try to fix that issue in the new version of the kernel library.

**Comment by ChriD** [comment]
I may check this now with the new Version. But first i have to save my playlists because who knows if host change works correct on the current raumfeld firmware

**Comment by ChriD** [comment]
This issue should be gone with version 1.2
