### ISSUE TITLE
build of raumserver/kernel/lib on linux x64

### ISSUE THREAD

**Issue by holli73** [ChriD/Raumserver#33]
hello,

i tried to build the cloned repositories but all failed with the make to the target directory because within the repo's the 'libs/_tmpBuild' directory is missing...

please add to the build files just one line f.ex.: buildX64.sh

```
#!/bin/bash
mkdir -p libs/_tmpBuild
...

```

so the next time i pull - i don't to change it again

thanks
holli

PS: within the 'Raumserver/source/RaumserverDaemon/bin/linux_x64' are the new compiled binaries but the xml is named 'raumserver.xml' and on starting i got 'Can not open settings file '...settings.xml' so i created a symlink 'ln -s raumserver.xml settings.xml' and now i get '{"raumkernelLib":"1.0.2","raumserverLib":"1.0.2"}' -> cool

**Comment by ChriD** [comment]
Added the suggested mkdir and clarified the "settings.xml"
