### ISSUE TITLE
RaumsrvInstaller doesn't work on Mac OSX

### ISSUE THREAD

**Issue by kenny85r** [ChriD/Raumserver#38]
If I try to start RaumsrvInstaller in Terminal, this error occurred:
cannot execute binary file

Could someone help me?

THX.

**Comment by ChriD** [comment]
The installer is not meant to run on Mac OSX
There are only binaries for linux and windows.

But you may install the raumserver manual on the raumfeld devices

**Comment by kenny85r** [comment]
Thank u.
And how Can I do this?
Am 11.11.2016 4:47 PM schrieb "Christian" notifications@github.com:
