### ISSUE TITLE
latest pull - breakes build?

### ISSUE THREAD

**Issue by holli73** [ChriD/Raumserver#39]
hello,

i did pull the latest to try the changes (cpu usage) but on the make i get:

```
g++-5 -m64 -std=c++11 -fPIC -Wall -Wno-unknown-pragmas -Wno-unused-parameter -funwind-tables -Wextra -O0 -c -pthread -fno-omit-frame-pointer  -g  -I includes/ -I ../../../RaumkernelLib/source/includes/ -I ../../../RaumserverLib/source/includes/ -I includes/libunwind/ -MMD -c -o build/obj-dyn/RaumserverDaemon.o RaumserverDaemon.cpp
RaumserverDaemon.cpp: In function ‘int main(int, char**)’:
RaumserverDaemon.cpp:208:86: warning: format not a string literal and no format arguments [-Wformat-security]
     syslog (LOG_NOTICE, std::string("Working directory: " + workingDirectory).c_str());
                                                                                      ^
g++-5 -m64 -pthread -static-libgcc -static-libstdc++ -rdynamic -Wl,--no-as-needed -ldl -Llibs/linux_X64/ -Wl,-rpath,libs  -o build/raumsrvDaemonDyn build/obj-dyn/RaumserverDaemon.o -Bdynamic -lraumserver -lraumkernel -lunwind -lunwind-x86_64
libs/linux_X64//libraumkernel.so: undefined reference to `OpenHome::Net::CpDeviceCpp::Udn[abi:cxx11]() const'
libs/linux_X64//libraumkernel.so: undefined reference to `OpenHome::Net::CpDeviceCpp::GetAttribute(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
collect2: error: ld returned 1 exit status
makefile:85: recipe for target 'build/raumsrvDaemonDyn' failed
make: *** [build/raumsrvDaemonDyn] Error 1
cp: cannot stat 'build/raumsrvDaemonDyn': No such file or directory
cp: cannot stat 'build/raumsrvDaemonStat': No such file or directory
rm -f  build/raumsrvDaemonDyn build/raumsrvDaemonStat build/obj-dyn/RaumserverDaemon.o build/obj-stat/RaumserverDaemon.o build/obj-dyn/RaumserverDaemon.d
rm -rf build/obj-dyn/ build/obj-stat/
```

i did pull/rebuild the kernel/kernellib and copied the new libs but i cant get the raumserverdeamon to build

any idea?

thanks
holli

PS: maybe you could use the "build" path within copy actual files script.

**Comment by ChriD** [comment]
O sorry, I have changed gcc from 4.9 to 5.0 but the new ohNet (built with gcc5) libs were not commited to the repository. Thats where the error comes from.
I have pushed them now to the repo. Please pull and rebuild all 3 repos again

> PS: maybe you could use the "build" path within copy actual files script.

I don't understand. If you have pulled the 3 repos you do not have to copy any files. The build scripts will do this automaticaly. The only thing to to is that you have to build the 3 Repos in the correct order
1 RaumkernelLib
2 RaumserverLib
3 RaumserverDaemon

And at the end you will get a "bin"  directory in the raumserverDaemon folder with the binaries (static and dynamic, you can choose which you want)

**Comment by holli73** [comment]
hello,

with the latest pull - i was able to compile 
@ PS: i think it was just to late - it did work without any changes to any files for the raumserverdeamon with the latest pull

thanks
holli
