### ISSUE TITLE
Cannot access 'updateId' header through CORS requests

### ISSUE THREAD

**Issue by Bonilla** [ChriD/Raumserver#46]
In version 1.0.1 `Access-Control-Allow-Origin: *` has been added to the Raumserver configuration making it possible to access the server's JSON objects through CORS. However, long polling through CORS is still not fully supported. Chrome for example returns:

> Refused to get unsafe header 'updateId'

It seems that "updateId" has not been whitelisted in Access-Control-Expose-Headers. Could you please add the following to the server configuration:

`Access-Control-Expose-Headers: updateId`

Thanks and keep up the great work! :)

**Comment by ChriD** [comment]
Yes, I can do that.

**Comment by ChriD** [comment]
I have done that
