### ISSUE TITLE
raumserver von hand installieren auf connector

### ISSUE THREAD

**Issue by abercrombie1892** [ChriD/Raumserver#49]
hallo,

ich bin langsam am verzweifeln. der connector ist auf software 1.60.1. wie bekomme ich das ganze auf dem connector installiert. muss es leider per hand machen da nur osx zur verfügung steht.

habe schon den ssh zugang und kann mich mit scp verbinden. habe die arm5 und arm7 schon probiert, jeweils die rechte auf 777 geändert. kann einfach keine verbindung aufbauen.

mfg. frank

**Comment by ChriD** [comment]
Connector 1: ARMv5
Connector 2: ARMv7

Binaries nach /etc/raumfeld/raumserver kopieren (raumserver ordner erstellen)
Und dann noch das S99raumserver script vom binary verzeichnis nach /etc/init.d/ kopieren.
Danach reboot durchführen (reboot als ssh command oder 'hard' reboot (strom aus / an)

Dann nach reboot etwa ne Minute warten und der server sollte laufen
