### ISSUE TITLE
Umfrage: Raumfeld-Server für Synology

### ISSUE THREAD

**Issue by NetHans** [ChriD/Raumserver#54]
Hallo,

mich würde mal interessieren, ob jemand Interesse daran hätte, den Raumfeld-Server inkl. einer eventuell möglichen GUI auf einer Synology-Box zu installieren?

**Comment by thedudede** [comment]
Ich gerne, allerdings mache ich das auch schon 
Hier findest du ein docker-image
https://hub.docker.com/r/gutmensch/raumserver/
das läuft wunderbar auf meine DS1515+

**Comment by NetHans** [comment]
Was soll ich sagen, dass es dann doch so einfach wird, hätte ich nicht erwartet. Danke für den Tipp.

So kann ich mir die Zeit sparen, mich mit der Entwicklung von Synology-Paketen zu beschäftigen ;-)
