### ISSUE TITLE
terminate called after throwing an instance of 'OpenHome::NetworkError'

### ISSUE THREAD

**Issue by omegagalvani** [ChriD/Raumserver#7]
Hi ChriD!

Vorab großes Dankeschön, dass durch dich endlich mal auch Raumfeld bei Interconnectivity vorne mitspielt!

Ich möchte Raumfeld mit FHEM über Raspberry Pi 2b nutzen und versuche daher deinen RaumServer zu installieren. Bislang bin ich gescheitert - wahrscheinlich durch meine Unerfahrenheit mit Raspbian Scripting.

Ich habe den RaumServer ARMv6 runtergeladen, entpackt und dann den ganzen Ordner mit RWX-Rechten versehen. Beim Starten von raumServerStart.sh startet der Server und bricht immer wieder mit "terminate called after throwing an instance of 'OpenHome::NetworkError'" ab.

Voran könnte dies liegen?
Wie kann ich dann den RaumServer auf dauerbetrieb halten ohne Abbruch durch Schließen des Terminals?
Und schließlich, wie kann ich den einmal laufenden RaumServer in FHEM einbinden?

Beste Grüße,
Alex

**Comment by omegagalvani** [comment]
Hi ChriD,

im fault Ordner übrigens noch folgende Mitteilung:
"signal 6 (Aborted), address is 0x17bb from 0x7677af50

[bt]: (1) /lib/arm-linux-gnueabihf/libc.so.6 : gsignal+0x38 [0x7677af50]
[bt]: (2) /lib/arm-linux-gnueabihf/libc.so.6 : gsignal+0x38 [0x7677af50]"

Beste Grüße,
Alex

**Comment by ChriD** [comment]
Da habe ich leider gesagt keine Ahnung. 
Es scheint so als ob es irgend ein Problem bei der Initialisierung des Netzwerkadapters gibt.
Du kannst auf die Neue Version warten und schaun ob es dann dort funktioniert, oder du versuchst mal einen anderen Netzwerkadapter in den Settings reinzuschreiben

**Comment by omegagalvani** [comment]
Hi ChriD,

vielen Dank für die Antwort!
Ich bin mir nicht sicher, ob ich die Raspbian Installation korrekt gemacht habe. mit welchen codes installiert man den raumserver gewöhnlich?

Beste Grüße,
Alex

**Comment by ChriD** [comment]
Depreciated version. Please check the new version!
