### ISSUE TITLE
LoadContainer vs. LoadSingle

### ISSUE THREAD

**Issue by rainerz1964** [ChriD/Raumserver#72]
In my code I first access the Favorites in my RF system via /raumserver/data/getMediaList?id=0%2FFavorites%2FMyFavorites. Favorites in my case contains a list of Radio stations. When using  loadContainer with one of the resulting Favorites it doesn't work, however, loadSingle works.

The documentation indicates that loadContainer should work as well. Do you have any idea of what is going wrong?

**Comment by ChriD** [comment]
loadContainer only works for "containers" 
"Containers" are for example Albums or any other items which contains subitems. A Radio station doesn't have subitems and therefore it cant be loaded with loadContainer

BTW: Raumserver was replaces
d long ago  by "node-raumserver"

**Comment by rainerz1964** [comment]
That makes sense. Thanks for the clarification.

node-raumserver is the one I am using.
