### ISSUE TITLE
Result XML from device does not contain DIDL-Lite block!

### ISSUE THREAD

**Issue by rwitkamp** [ChriD/Raumserver#9]
Hello,

I downloaded the most recent RaumServer from Bassmaniacs and use it in my Raumfeld environment with multiple Raumfeld devices. My central device is a Raumfeld Expand. Sometimes, when a device is playing, it stops when I send commands to another Raumfeld device with Raumserver. In the application.log I can find the log record 'Result XML from device does not contain DIDL-Lite block!' at the time that happens. I then have to send the 'play' command to the device that stopped to have it playing again.

I have this problem both on a Windows as a Linux (Fedora 21) installation.

Does anybody know how to solve this?

Regards,

Ron Witkamp

**Comment by ChriD** [comment]
The error of the DIDL-Lite block is a bug in the current raumserver version but it should not stop any other renderes from playing. Which commands do you send which will stop the devices from playing?

For your info: The raumserver was redesigned and the new redesigned Version (this one here on github) will be available soon. Erros in the 'old' Version will not be fixed anymore.

**Comment by rwitkamp** [comment]
Good to hear there is a new version coming. I can reproduce the error quite often, this is what I see in my log. Keuken is playing normally, then I send a wake-up to my speaker in my bedroom named Ron&Judith, then Keuken stops at the wakeUpTimer command, ath the same moment the error occurs in the logfile.

10:33:50.221936 INFO    Configuration service found! (Location: http://10.0.0.24:60556/83836c18-c136-4dc3-a018-12c8e6376004.xml)
10:33:50.222037 INFO    Requesting list of zones present on the Host
10:34:03.133757 INFO    Raumkern is ready for duty!
12:15:30.109003 INFO    Request received (/raumserver/room/Keuken/createZone?force=true)
12:15:34.733310 INFO    Request received (/raumserver/room/Keuken/volume?value=30)
12:15:36.008247 INFO    Request received (/raumserver/room/Woonkamer/addToZone?room=Keuken)
12:15:40.624831 INFO    Request received (/raumserver/room/Woonkamer/volume?value=50)
12:15:41.899079 INFO    Request received (/raumserver/room/Keuken/loadPlayList?name=NPO%20Radio%202)
12:15:48.008292 INFO    Request received (/raumserver/room/Keuken/play)
12:16:31.129767 INFO    Request received (/raumserver/room/Ron&Judith/createZone?force=true)
12:16:35.714911 INFO    Request received (/raumserver/room/Ron&Judith/loadPlayList?name=NPO%20Radio%202)
12:16:41.825391 INFO    Request received (/raumserver/room/Ron&Judith/wakeUpTimer?time=45&fadeInTime=3&maxVolume=30&fadeOutTime=3)
12:16:49.186299 ERROR   Result XML from device does not contain DIDL-Lite block!

**Comment by ChriD** [comment]
Close the issue because its from the depreciated old version
